spring.application.name=notification
server.port=7050

eureka.client.service-url.defaultZone=
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=
spring.rabbitmq.port=

management.endpoints.web.exposure.include=health,info